- go.mod
- handlers.go
> Feature: #9 Use AddVEvent

- modules.go
add modules 'edit-byid' and 'edit-bysummary-regex'
> [Modules] edit-byid & edit-bysummary-regex

- modules.go
> Add save-to-file module

- handlers.go
- main.go
- notifier.go
- templates/nav.html
- templates/subscribe.html
- templates/unsubscribe.html
> Frontend für Mail

- templates/monthly.html
> Implement #102

- handlers.go
- templates/monthly.html
> If immutable past is active edit button should not be displayed on past events

- templates/edit.html
- templates/index.html
- templates/settings.html
Redirects on index.html and settings.html.
When a new profile is saved, redirection happens after 1 second so that the user gets a chance to read the 'success' message:
https://user-images.githubusercontent.com/18506129/222954707-648780ef-f6d8-4d1d-8b91-321fae4b383a.mp4
> Weiterleitung zum kurs der in den einstellungen gespeichert ist

- templates/monthly.html
> Display an error if the token saved in local storage is invalid

- notifier.go
> More Verbose Error Messages for notifiers

- templates/index.html
> Add "remember me" option to profile selection

- templates/static/js/calendar.js
See #140 for a screenshot.
Closes #140
> Add clickable location links if possible

- config.go
- config.yml.example
- handlers.go
- templates/edit.html
- templates/head.html
- templates/howto-users.html
- templates/index.html
- templates/modules.html
- templates/monthly.html
- templates/nav.html
- templates/settings.html
- templates/static/css/main.css
- templates/static/media/favicon.svg
- templates/subscribe.html
- templates/unsubscribe.html
- Changed Page Titles
- Added favicon to navbar-brand
Resolves #152
> profile name as title & Favicons

- cmd/ical-relay/legacyconfig.go
loop only saved the last rule
used correct variable in loop
> fix config upgrade only getting one rule

- cmd/ical-relay/legacyconfig.go
added param id instead of regex
Sorry, war noch ein Bug drinnen
> fix regex rule upgrade

- cmd/ical-relay/api.go
- cmd/ical-relay/go.mod
- cmd/ical-relay/go.sum
- cmd/ical-relay/handlers.go
- cmd/ical-relay/templates/calendar.html
- cmd/ical-relay/templates/footer.html
- cmd/ical-relay/templates/newevent.html
- cmd/ical-relay/templates/static/media/plus.svg
> [Frontend] Add Event

- cmd/ical-relay/database.go
No fields selected in subquery
> DB: fix dbRemoveAllProfileSources

- cmd/ical-relay/templates/admin.html
- cmd/ical-relay/templates/edit.html
- cmd/ical-relay/templates/newevent.html
- cmd/ical-relay/templates/settings.html
Modified checks if a token is selected.
App works now with no selected token as expected.
Changes are relatively large due to formatter.
> Fix error messages and weird behaviour when no profile is selected

- .gitignore
- cmd/ical-relay/templates/calendar.html
- cmd/ical-relay/templates/static/js/calendar.js
> fix(frontend): allow same day editing

- cmd/ical-relay/api.go
- cmd/ical-relay/config.go
- cmd/ical-relay/database.go
> feat(api): show private profiles when authorized

- pkg/modules/actions.go
> fix(backend): allow for empty description etc. fields

- cmd/ical-relay/api.go
- cmd/ical-relay/config.go
- cmd/ical-relay/legacyconfig.go
> fix(backend): error handling is am start

- cmd/ical-relay/templates/calendar.html
Added a check for sundays to display the following week on sundays. For this the date objct that was passed to the update calendar function had to be changed from start of current Type to start of day
> updated calendar to show next week on Sundays

- cmd/ical-relay/api.go
- cmd/ical-relay/templates/calendar.html
- cmd/ical-relay/templates/static/css/main.css
- cmd/ical-relay/templates/static/js/api.js
- cmd/ical-relay/templates/static/js/dnd.js
> feat: add ics file drag&drop

- cmd/ical-relay/api.go
- cmd/ical-relay/config.go
- cmd/ical-relay/config_test.go
- cmd/ical-relay/data.go
- cmd/ical-relay/database.go
- cmd/ical-relay/dbDataStore.go
- cmd/ical-relay/fixtures/testconfig.yaml
- cmd/ical-relay/handlers.go
- cmd/ical-relay/legacyconfig.go
- cmd/ical-relay/main.go
- cmd/ical-relay/notifier.go
- cmd/ical-relay/profiles.go
This is ongoing work to entirely split the database part of ical-relay and the config part.
> Introduce DataStore interface, split db and conf

- .gitignore
- README.md
- cmd/ical-relay/api.go
- cmd/ical-relay/data.yml.example
- pkg/datastore/database.go
- pkg/datastore/db.sql
- pkg/datastore/dbDataStore.go
- pkg/datastore/fileDataStore.go
This is a PR fixing some issues I discovered after the merge of the merge of the large PR "Internal Data Handling and Representation rework"
A more detailed description will follow.
ToDo:
- Add tests for discovered issues
> Fix/improve various DataStore issues
